### PR TITLE
Allow tileset handling of gzipped and non-gzipped tilesets

### PR DESCRIPTION
**Pull request by shehzan10**
Automatically detects whether a tileset is gzipped or not using the gzipped header, then applies the content encoding header.

### CODE REVIEW

**Comment by lilleyse** [comment]
Thanks! Very useful to have.

**Comment by lilleyse** [comment]
@mramato is this something we would want in Cesium's `server.js`? It was requested on the forum here: https://groups.google.com/forum/#!topic/cesium-dev/8HSOsfRmGMM

**Comment by mramato** [comment]
I'm not sure why we would add support for it in Cesium, since we don't include any gzipped tilesets or data, right?

It sounds like they are using the NYC sample data we have up on cesiumjs.org, in my opinion we should change that sample to not include gzipped data.

That being said, if we just want to make our users happy and avoid any potential headaches, I'm not again adding it "just because", but I do have some minor performance concerns, since it means every files gets read twice.

Perhaps we can punt for now and revisit when we handle the http2 PR.  The server is long overdue for an update either way.

**Comment by xuezhaokun** [comment]
If Cesium could provide the ungzipped NYC sample data, that would be great.

**Comment by lilleyse** [comment]
Until then you can use the `ungzip` command in `https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/tools`

**Comment by xuezhaokun** [comment]
@lilleyse This looks really helpful. I will give a try. Thanks for help!

**Comment by pjcozzi** [comment]
Late to the part here, but this is a common issue so I would just add this to Cesium's server.js; it will not be a maintenance issue.

@shehzan10 can you please make the change?

**Pull request merged**
